[package]
name = "greybot"
version = "0.1.0"
edition = "2018"
authors = ["SarahGreyWolf <m.sarahgreywolf@outlook.com>"]

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
hyper = {version="0.14.11", features = ["client"]}
ron = "0.6.4"
